### PR TITLE
Environment variable for static linking

### LINKED ISSUE #8: Install with statically linked libraries
I'm installing with MUMPS built from source, which by default builds static libraries. I can link these libraries with Pymumps if I compile them with -fPIC, but there is currently no way to specify libraries to link statically, which I believe should be done via the `extra_objects` argument in `Extension`. I think this could also be accomplished by prepending the location of my static MUMPS libraries to `PYMUMPS_SETUP_LIBRARY_DIRS`, but this would not be reliable if I had static and dynamic libraries in the same location.

### PR DESCRIPTION
**Pull request by Robbybp**
Check the `PYMUMPS_SETUP_EXTRA_OBJECTS` environment variable to allow users to specify, for example, static libraries to link. 

Fixes #8

### CODE REVIEW

**Comment by sdrave** [comment]
Hi @Robbybp, thanks for the PR! However, I am thinking about ditching the `setup_env` branch in favor of the more generic approach of [passing the options to pip](https://stackoverflow.com/questions/18783390/) via `--global-option`. This is also what is used in the [conda-forge recipe](https://github.com/conda-forge/pymumps-feedstock/blob/master/recipe/meta.yaml).

Could you check if
```
pip install pymumps --global-option="build_ext" --global-option="-O..."
```
works for you?

**Comment by Robbybp** [comment]
Hi @sdrave, that works for me, thanks! What is the equivalent way to specify these options when running `python setup.py build_ext` or `python setup.py develop`?

**Comment by sdrave** [comment]
Everything you pass as `--global-option` after `--global-option="build_ext"` is passed to the `build_ext` command. So the same options (in particular `-O`) should be valid with `python setup.py build_ext` as well.

**Comment by sdrave** [comment]
Closing in favor of #10.

**Pull request closed without merging**
